# Generated by Django 4.1.4 on 2022-12-22 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='担当者名')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='店舗ID')),
                ('name', models.CharField(max_length=30, verbose_name='店舗名')),
                ('status', models.CharField(choices=[('フランチャイズ契約', 'フランチャイズ契約'), ('ライセンス契約', 'ライセンス契約'), ('解約済み', '解約済み')], max_length=15, verbose_name='契約ステータス')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.manager', verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='記録年月')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.store', verbose_name='店舗')),
            ],
            options={
                'unique_together': {('store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SaleAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PC')),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='スマホ')),
                ('app', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='アプリ')),
                ('store_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.storedata', verbose_name='データ')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PC')),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='スマホ')),
                ('app', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='アプリ')),
                ('store_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.storedata', verbose_name='データ')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='PC')),
                ('phone', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='スマホ')),
                ('app', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='アプリ')),
                ('store_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.storedata', verbose_name='データ')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='PC')),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='スマホ')),
                ('app', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='アプリ')),
                ('store_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.storedata', verbose_name='データ')),
            ],
        ),
    ]
