# Generated by Django 4.1.4 on 2022-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='店舗ID'),
        ),
    ]
