# Generated by Django 4.1.4 on 2022-12-22 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 22), verbose_name='契約日'),
            preserve_default=False,
        ),
    ]
